### ISSUE TITLE
Sorting data frame by a column

### ISSUE THREAD

**Issue by mdmaidulislamchowdhury** [jdebacker/CompEcon_Fall17#23]
I am trying to sort by Dataframe by sorting a column. I am using the following code

radio_2.sort_values(by='Index',ascending=True)

Here, 'radio_2' is my data frame name and 'Index' is the column by which I want to sort my entire data frame. The code is neither giving any error nor executing any change in the data frame. Could you please suggest me a way to sort my data frame by sorting a column?

**Comment by jdebacker** [comment]
@mdmaidul Good question.  

When you do `radio_2.sort_values(by='Index',ascending=True)`, the data frame, `radio_2` is sorted an is returned as an object.  So if you did:

`radio_3 = radio_2.sort_values(by='Index',ascending=True)`

This would create a new data frame the is the sorted version of `radio_2`.  If you don't want to create another data frame, but want `radio_2` sorted to work with later, you will want to utilize the `inplace` keyword argument.  i.e., what you want to write is:

`radio_2.sort_values(by='Index',ascending=True, inplace=True)`

This will edit the data frame `radio_2` and it will now be sorted in the way you specify.

**Comment by mdmaidulislamchowdhury** [comment]
It is working now!! Thank you very much!
